name: Upload specs to Firebase Storage

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          yarn: true
          yarn-version: latest

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Upload tarball if specs changed
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        run: |
          git diff --quiet ${{github.event.before}} ${{github.sha}} specs || yarn specs:upload
